# Generated by Django 5.1.4 on 2026-07-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
